from rocker/r-base

run apt-get update
run apt-get install -t unstable -y libcurl4-openssl-dev
run apt-get install -t unstable -y libssl-dev
run apt-get install -t unstable -y libhdf5-dev
run R -e "install.packages('devtools')"
run R -e "install.packages('h5')"